# -*- coding: utf-8 -*-
"""Traffic_Sign_Classification_PyTorch_Full (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iz9rg8ftiTmtBZwJc9PScQerTy2HALFy

# Deep Learning Analysis: Traffic Sign Classification (GTSRB)

---

## 1.1 Problem Definition

**Scientific/Engineering Question:** Can deep convolutional neural networks reliably classify traffic sign images into 43 semantic classes (speed limits, stop, yield, etc.) under real-world conditions (small resolution, varying illumination)?

**Why This Matters:** Autonomous driving and driver-assistance systems depend on accurate sign recognition. Misclassifying a "30 km/h" as "80 km/h" or missing a stop sign has safety-critical consequences. GTSRB is a standard benchmark for evaluating vision models on this task.

---

## 1.2 Methodological Justification

**Architecture Choice:** CNNs are selected because they learn hierarchical spatial features (edges → textures → shapes) directly from pixels, which is essential for recognizing signs with distinct geometric and color patterns. A shallow MLP on raw pixels ignores spatial structure.

**Training Strategy:**
- **Optimizer:** Adam (adaptive learning rate, good default for CNNs)
- **Regularization:** Dropout(0.25) in Complex CNN; BatchNorm for stability
- **Hyperparameters:** 20 epochs, batch size 32, lr=1e-3 (Complex CNN)
- **Scheduling:** No explicit LR schedule; early stopping possible via validation loss
- **Reproducibility:** Random seeds fixed for `random`, `numpy`, and `torch`
- **Hyperparameter exploration:** See section below (lr, batch size)

---

## 1.3 Baseline Comparison (Mandatory)

We compare our **deep CNN** against a **simple baseline** (Logistic Regression on flattened pixels) to quantify the value added by convolutional architecture. See the "Simple Baseline: Logistic Regression" section below.

---

## 1.4 Analytical Insights

Beyond raw accuracy, we provide:
- **Confusion matrix** to identify which sign classes are confused
- **Per-class accuracy** and hardest classes
- **Error analysis** with sample misclassifications
- **Baseline vs CNN comparison** table

# Traffic Sign Recognition System

**Importing Modules**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image, ImageFilter
import os
import random
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset, Dataset
import kagglehub

"""**Reproducibility:** Set random seeds for `random`, `numpy`, and `torch` so results are reproducible across runs."""

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
set_seed(42)
print("Random seeds set for reproducibility.")

"""**1-1) Download Data & 1-2) Store Data, Labels in Lists**"""

# 1-1) Download GTSRB data via kagglehub
data_path = kagglehub.dataset_download("meowmeowmeowmeowmeow/gtsrb-german-traffic-sign")
print("Dataset path:", data_path)

# Find train folder
data_path = Path(data_path)
train_dir = None
for p in [data_path / "Train", data_path / "train",
          data_path / "GTSRB" / "Final_Training" / "Images",
          data_path / "GTSRB_Final_Training_Images" / "GTSRB" / "Final_Training" / "Images"]:
    if p.exists():
        train_dir = p
        break
if train_dir is None:
    raise FileNotFoundError(f"Train folder not found. Contents: {list(data_path.iterdir())}")
print("Train folder:", train_dir)

data = []
labels = []
classes = 43
cur_path = train_dir

"""**Preprocessing Image**"""

# 1-2) Preprocessing: load images, resize to 30x30, label by class {0,1,...,N}
for i in range(classes):
    # Try both "0" and "00000" style folder names
    for folder_name in [str(i), f"{i:05d}"]:
        path = cur_path / folder_name
        if path.exists():
            break
    if not path.exists():
        continue
    for f in path.iterdir():
        if f.suffix.lower() in ('.ppm', '.png', '.jpg', '.jpeg'):
            try:
                image = Image.open(f).convert('RGB')
                image = image.resize((30, 30))
                data.append(np.array(image))
                labels.append(i)
            except Exception as e:
                print(e)
print(f"Loaded {len(data)} images")

"""**Converting List into a Numpy Array**"""

data = np.array(data)
labels = np.array(labels)

"""**Save Labels and Data for further use**"""

os.makedirs('./trained', exist_ok=True)
np.save('./trained/data', data)
np.save('./trained/target', labels)

"""**Load Data and Labels**"""

data = np.load('./trained/data.npy')
labels = np.load('./trained/target.npy')

print('Shape of Image Data: ' + str(data.shape))
print('Shape of Labels Data: ' + str(labels.shape))

"""**1.3 Simple Baseline: Logistic Regression (Mandatory Comparison)**

Fit Logistic Regression on flattened pixels (no spatial structure) to quantify the value added by the CNN architecture.

*Run data load and train_test_split cells above first. If you get `NameError`, run those cells and retry.*
"""

# Ensure split exists — run data load + split cells above first if you get NameError
if 'x_train' not in globals():
    try:
        x_trainval, x_test, y_trainval, y_test = train_test_split(data, labels, test_size=0.15, random_state=0)
        x_train, x_val, y_train, y_val = train_test_split(x_trainval, y_trainval, test_size=15/85, random_state=0)
    except NameError:
        raise RuntimeError("Run the data loading and train_test_split cells above first.")

# Flatten images for baseline (N, 30*30*3) = (N, 2700)
X_train_flat = x_train.reshape(x_train.shape[0], -1) / 255.0
X_test_flat = x_test.reshape(x_test.shape[0], -1) / 255.0

# Simple baseline: Logistic Regression
clf_baseline = LogisticRegression(max_iter=500, C=0.1, solver='lbfgs', n_jobs=-1)
clf_baseline.fit(X_train_flat, y_train)
y_pred_baseline = clf_baseline.predict(X_test_flat)
acc_baseline = (y_pred_baseline == y_test).mean()
print(f"Baseline (Logistic Regression) Test Accuracy: {acc_baseline:.4f}")

"""*We can see that the shape of Image data and Labels is same*"""

# 70% train, 15% validation, 15% test
x_trainval, x_test, y_trainval, y_test = train_test_split(data, labels, test_size=0.15, random_state=0)
x_train, x_val, y_train, y_val = train_test_split(x_trainval, y_trainval, test_size=15/85, random_state=0)
print(f'Train: {len(x_train)} ({100*len(x_train)/len(data):.1f}%) | Val: {len(x_val)} (15%) | Test: {len(x_test)} (15%)')

print('Train:', x_train.shape, y_train.shape)
print('Val:  ', x_val.shape, y_val.shape)
print('Test: ', x_test.shape, y_test.shape)

"""**Convert data for PyTorch** (labels stay as class indices; CrossEntropyLoss handles them)"""

# Convert to tensors and normalize to [0,1]
x_train_t = torch.FloatTensor(x_train).permute(0, 3, 1, 2) / 255.0  # NCHW
x_val_t = torch.FloatTensor(x_val).permute(0, 3, 1, 2) / 255.0
x_test_t = torch.FloatTensor(x_test).permute(0, 3, 1, 2) / 255.0
y_train_t = torch.LongTensor(y_train)
y_val_t = torch.LongTensor(y_val)
y_test_t = torch.LongTensor(y_test)
train_dataset = TensorDataset(x_train_t, y_train_t)
val_dataset = TensorDataset(x_val_t, y_val_t)
test_dataset = TensorDataset(x_test_t, y_test_t)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

"""**Building Model (Basic CNN)**"""

# Basic CNN: 2 conv layers + 1 fully connected
class BasicCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 32, 3)   # 30->28
        self.conv2 = nn.Conv2d(32, 64, 3)  # 14->12
        self.pool = nn.MaxPool2d(2, 2)     # 28->14, 12->6
        self.fc1 = nn.Linear(64 * 6 * 6, 128)
        self.fc2 = nn.Linear(128, 43)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool(torch.relu(self.conv2(x)))
        x = torch.flatten(x, 1)
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = BasicCNN()
print('Basic CNN ready')
print(model)

"""**Compile & Train Model (PyTorch)**"""

device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
model = model.to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters())

epochs = 20
history = {'loss': [], 'accuracy': [], 'val_loss': [], 'val_accuracy': []}
for ep in range(epochs):
    model.train()
    train_loss, correct, total = 0, 0, 0
    for bx, by in train_loader:
        bx, by = bx.to(device), by.to(device)
        optimizer.zero_grad()
        out = model(bx)
        loss = criterion(out, by)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
        correct += (out.argmax(1) == by).sum().item()
        total += by.size(0)
    history['loss'].append(train_loss / len(train_loader))
    history['accuracy'].append(correct / total)

    model.eval()
    val_loss, vcorrect, vtotal = 0, 0, 0
    with torch.no_grad():
        for bx, by in val_loader:
            bx, by = bx.to(device), by.to(device)
            out = model(bx)
            val_loss += criterion(out, by).item()
            vcorrect += (out.argmax(1) == by).sum().item()
            vtotal += by.size(0)
    history['val_loss'].append(val_loss / len(val_loader))
    history['val_accuracy'].append(vcorrect / vtotal)
    print(f"Epoch {ep+1}/{epochs} - loss: {history['loss'][-1]:.4f} - accuracy: {history['accuracy'][-1]:.4f} - val_loss: {history['val_loss'][-1]:.4f} - val_accuracy: {history['val_accuracy'][-1]:.4f}")

"""**Accuracy**"""

plt.figure(0)
plt.plot(history['accuracy'], label='training accuracy')
plt.plot(history['val_accuracy'], label='val accuracy')
plt.title('Accuracy')
plt.xlabel('epochs')
plt.ylabel('accuracy')
plt.legend()
plt.show()

"""Here what we can observe is that for 20 Epochs

*Accuracy is 0.9422*

*Validation Accuracy is 0.9843*

**Loss**

**Hyperparameter Exploration:** Train Basic CNN with different learning rates and batch sizes to compare convergence.
"""

# Hyperparameter exploration: lr and batch size (10 epochs each for speed)
HP_EPOCHS = 10
configs = [
    {"lr": 1e-4, "batch_size": 32, "label": "lr=1e-4, bs=32"},
    {"lr": 5e-4, "batch_size": 32, "label": "lr=5e-4, bs=32"},
    {"lr": 1e-3, "batch_size": 32, "label": "lr=1e-3, bs=32"},
    {"lr": 1e-3, "batch_size": 64, "label": "lr=1e-3, bs=64"},
]
hp_histories = {}

for cfg in configs:
    set_seed(42)
    loader = DataLoader(train_dataset, batch_size=cfg["batch_size"], shuffle=True, num_workers=0)
    m = BasicCNN().to(device)
    opt = torch.optim.Adam(m.parameters(), lr=cfg["lr"])
    hist = {"val_accuracy": []}
    for ep in range(HP_EPOCHS):
        m.train()
        for bx, by in loader:
            bx, by = bx.to(device), by.to(device)
            opt.zero_grad()
            loss = criterion(m(bx), by)
            loss.backward()
            opt.step()
        m.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for bx, by in val_loader:
                bx, by = bx.to(device), by.to(device)
                correct += (m(bx).argmax(1) == by).sum().item()
                total += by.size(0)
        hist["val_accuracy"].append(correct / total)
    hp_histories[cfg["label"]] = hist
    print(f"{cfg['label']}: best val_acc = {max(hist['val_accuracy']):.4f}")

plt.figure(figsize=(10, 5))
for label, hist in hp_histories.items():
    plt.plot(hist["val_accuracy"], label=label, marker='o', markersize=3)
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Hyperparameter Exploration — Basic CNN")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

plt.plot(history['loss'], label='training loss')
plt.plot(history['val_loss'], label='val loss')
plt.title('Loss')
plt.xlabel('epochs')
plt.ylabel('loss')
plt.legend()
plt.show()

"""---
## Complex CNN

Deeper model with more capacity (4 conv blocks, BatchNorm, Dropout), built after analyzing Basic CNN results.
"""

# Complex CNN: 4 conv blocks (32→64→128→256), BatchNorm, Dropout, deeper FC
class ComplexCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.conv3 = nn.Conv2d(64, 128, 3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        self.conv4 = nn.Conv2d(128, 256, 3, padding=1)
        self.bn4 = nn.BatchNorm2d(256)
        self.pool = nn.MaxPool2d(2, 2)
        self.drop = nn.Dropout(0.25)
        self.fc1 = nn.Linear(256 * 1 * 1, 256)  # 30→15→7→3→1 after 4 pools
        self.fc2 = nn.Linear(256, 43)

    def forward(self, x):
        x = self.drop(self.pool(torch.relu(self.bn1(self.conv1(x)))))
        x = self.drop(self.pool(torch.relu(self.bn2(self.conv2(x)))))
        x = self.drop(self.pool(torch.relu(self.bn3(self.conv3(x)))))
        x = self.pool(torch.relu(self.bn4(self.conv4(x))))
        x = torch.flatten(x, 1)
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model_complex = ComplexCNN().to(device)
optimizer_complex = torch.optim.Adam(model_complex.parameters(), lr=1e-3)
print('Complex CNN ready')

# Train Complex CNN
history_complex = {'loss': [], 'accuracy': [], 'val_loss': [], 'val_accuracy': []}
epochs = 20
for ep in range(epochs):
    model_complex.train()
    train_loss, correct, total = 0, 0, 0
    for bx, by in train_loader:
        bx, by = bx.to(device), by.to(device)
        optimizer_complex.zero_grad()
        out = model_complex(bx)
        loss = criterion(out, by)
        loss.backward()
        optimizer_complex.step()
        train_loss += loss.item()
        correct += (out.argmax(1) == by).sum().item()
        total += by.size(0)
    history_complex['loss'].append(train_loss / len(train_loader))
    history_complex['accuracy'].append(correct / total)

    model_complex.eval()
    val_loss, vcorrect, vtotal = 0, 0, 0
    with torch.no_grad():
        for bx, by in val_loader:
            bx, by = bx.to(device), by.to(device)
            out = model_complex(bx)
            val_loss += criterion(out, by).item()
            vcorrect += (out.argmax(1) == by).sum().item()
            vtotal += by.size(0)
    history_complex['val_loss'].append(val_loss / len(val_loader))
    history_complex['val_accuracy'].append(vcorrect / vtotal)
    print(f"Epoch {ep+1}/{epochs} - loss: {history_complex['loss'][-1]:.4f} - acc: {history_complex['accuracy'][-1]:.4f} - val_acc: {history_complex['val_accuracy'][-1]:.4f}")

"""So we can observe that

*Feature loss is 0.2349*

*Validation loss is 0.0572*

**1.4 Analytical Insights:** Confusion matrix, per-class accuracy, error analysis
"""

# Get CNN predictions for analysis
model.eval()
y_pred_cnn = []
with torch.no_grad():
    for bx, _ in test_loader:
        bx = bx.to(device)
        out = model(bx)
        y_pred_cnn.extend(out.argmax(1).cpu().numpy())
y_pred_cnn = np.array(y_pred_cnn)

# Confusion matrix (Basic CNN)
cm = confusion_matrix(y_test, y_pred_cnn)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, cmap='Blues', cbar_kws={'label': 'Count'})
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix — Basic CNN (43 classes)')
plt.tight_layout()
plt.show()

# Per-class accuracy: hardest classes
class_acc = []
for c in range(43):
    mask = y_test == c
    if mask.sum() > 0:
        acc = (y_pred_cnn[mask] == y_test[mask]).mean()
        class_acc.append((c, acc, mask.sum()))
class_acc.sort(key=lambda x: x[1])
print("Hardest 5 classes (lowest accuracy):")
for c, acc, n in class_acc[:5]:
    print(f"  Class {c}: {acc:.3f} (n={n})")

# Sample misclassifications
wrong_idx = np.where(y_pred_cnn != y_test)[0]
if len(wrong_idx) > 0:
    n_show = min(6, len(wrong_idx))
    rng = np.random.default_rng(42)
    samp = rng.choice(wrong_idx, n_show, replace=False)
    fig, axes = plt.subplots(2, 3, figsize=(9, 6))
    for i, ax in enumerate(axes.flat):
        if i < len(samp):
            idx = samp[i]
            ax.imshow(x_test[idx])
            ax.set_title(f"True:{y_test[idx]} Pred:{y_pred_cnn[idx]}")
        ax.axis('off')
    plt.suptitle('Sample Misclassifications')
    plt.tight_layout()
    plt.show()

"""---
## Training with Data Augmentation (rotate, blur)

Apply random rotation and blur to training images to improve robustness. Compare accuracy with the baseline above.
"""

class AugmentedDataset(Dataset):
    """Dataset that applies random rotation and blur on each __getitem__."""
    def __init__(self, images, labels, rotate_deg=25, blur_prob=0.5):
        # images: numpy (N, H, W, 3) in [0,255] or tensor (N, 3, H, W) in [0,1]
        self.images = images if isinstance(images, np.ndarray) else images.numpy()
        if self.images.max() <= 1:
            self.images = (self.images * 255).astype(np.uint8)
        if self.images.shape[1] == 3:  # NCHW
            self.images = np.transpose(self.images, (0, 2, 3, 1))
        self.labels = labels
        self.rotate_deg = rotate_deg
        self.blur_prob = blur_prob

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        img = self.images[idx]
        img = Image.fromarray(img)
        if random.random() < 0.5:
            angle = random.uniform(-self.rotate_deg, self.rotate_deg)
            img = img.rotate(angle, fillcolor=(128, 128, 128))
        if random.random() < self.blur_prob:
            img = img.filter(ImageFilter.GaussianBlur(radius=random.uniform(0.5, 1.5)))
        x = np.array(img)
        x = torch.FloatTensor(x).permute(2, 0, 1) / 255.0
        return x, torch.tensor(self.labels[idx], dtype=torch.long)

# Build augmented train loader (test set stays unchanged)
aug_train_dataset = AugmentedDataset(x_train, y_train, rotate_deg=25, blur_prob=0.5)
aug_train_loader = DataLoader(aug_train_dataset, batch_size=32, shuffle=True, num_workers=0)
print("Augmented train loader ready (rotate ±25°, blur 50% prob)")

# Train a fresh model with augmented data
model_aug = BasicCNN().to(device)
optimizer_aug = torch.optim.Adam(model_aug.parameters())
history_aug = {'loss': [], 'accuracy': [], 'val_loss': [], 'val_accuracy': []}

epochs = 20
for ep in range(epochs):
    model_aug.train()
    train_loss, correct, total = 0, 0, 0
    for bx, by in aug_train_loader:
        bx, by = bx.to(device), by.to(device)
        optimizer_aug.zero_grad()
        out = model_aug(bx)
        loss = criterion(out, by)
        loss.backward()
        optimizer_aug.step()
        train_loss += loss.item()
        correct += (out.argmax(1) == by).sum().item()
        total += by.size(0)
    history_aug['loss'].append(train_loss / len(aug_train_loader))
    history_aug['accuracy'].append(correct / total)

    model_aug.eval()
    val_loss, vcorrect, vtotal = 0, 0, 0
    with torch.no_grad():
        for bx, by in val_loader:
            bx, by = bx.to(device), by.to(device)
            out = model_aug(bx)
            val_loss += criterion(out, by).item()
            vcorrect += (out.argmax(1) == by).sum().item()
            vtotal += by.size(0)
    history_aug['val_loss'].append(val_loss / len(val_loader))
    history_aug['val_accuracy'].append(vcorrect / vtotal)
    print(f"Epoch {ep+1}/{epochs} - loss: {history_aug['loss'][-1]:.4f} - acc: {history_aug['accuracy'][-1]:.4f} - val_acc: {history_aug['val_accuracy'][-1]:.4f}")

# Compare: Basic vs Complex vs Data Augmentation
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history['val_accuracy'], label='Basic CNN', marker='o', markersize=3)
plt.plot(history_complex['val_accuracy'], label='Complex CNN', marker='^', markersize=3)
plt.plot(history_aug['val_accuracy'], label='+ Augmentation', marker='s', markersize=3)
plt.title('Validation Accuracy Comparison')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history['val_loss'], label='Basic CNN', marker='o', markersize=3)
plt.plot(history_complex['val_loss'], label='Complex CNN', marker='^', markersize=3)
plt.plot(history_aug['val_loss'], label='+ Augmentation', marker='s', markersize=3)
plt.title('Validation Loss Comparison')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.tight_layout()
plt.show()

print(f"Basic CNN best val accuracy:  {max(history['val_accuracy']):.4f}")
print(f"Complex CNN best val accuracy: {max(history_complex['val_accuracy']):.4f}")
print(f"+ Augmentation best val accuracy: {max(history_aug['val_accuracy']):.4f}")

# Final evaluation on held-out test set (15%)
def eval_test(model, loader):
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for bx, by in loader:
            bx, by = bx.to(device), by.to(device)
            out = model(bx)
            correct += (out.argmax(1) == by).sum().item()
            total += by.size(0)
    return correct / total

# 1.3 Baseline vs Deep Model Comparison
acc_cnn = eval_test(model, test_loader)
print("Test set accuracy (held-out 15%):")
print(f"  Baseline (Logistic Regression): {acc_baseline:.4f}")
print(f"  Basic CNN:     {acc_cnn:.4f}")
print(f"  Complex CNN:   {eval_test(model_complex, test_loader):.4f}")
print(f"  + Augment:     {eval_test(model_aug, test_loader):.4f}")
print(f"\n  CNN gain over baseline: +{(acc_cnn - acc_baseline)*100:.1f} pp")

"""**Testing**"""

def testing(testcsv, data_root=None):
    df = pd.read_csv(testcsv)
    label = df["ClassId"].values
    imgs = df["Path"].values
    data_list = []
    for img in imgs:
        path = Path(img) if data_root is None else Path(data_root) / img
        if not path.exists():
            path = Path(data_root) / img.replace('\\', '/').split('/')[-1] if data_root else Path(img)
        image = Image.open(path).convert('RGB')
        image = image.resize((30, 30))
        data_list.append(np.array(image))
    x_test = np.array(data_list)
    return x_test, label

# Test.csv may be in dataset root; paths can be relative to data_path
test_csv = data_path / "Test.csv"
if not test_csv.exists():
    test_csv = data_path / "test.csv"
if not test_csv.exists():
    test_csv = "Test.csv"  # fallback
try:
    x_test_files, label_test = testing(test_csv, data_path)
    x_test_t_files = torch.FloatTensor(x_test_files).permute(0, 3, 1, 2) / 255.0
    has_test_csv = True
except Exception as e:
    print("Test.csv not found, skipping test set evaluation:", e)
    has_test_csv = False

if has_test_csv:
    model.eval()
    with torch.no_grad():
        out = model(x_test_t_files.to(device))
        y_pred = out.argmax(1).cpu().numpy()
    y_pred

"""**Accuracy With Test Data**"""

from sklearn.metrics import accuracy_score
if has_test_csv:
    print("Test set accuracy:", accuracy_score(label_test, y_pred))

torch.save(model.state_dict(), "./trained/TSR.pt")

"""**Loading the model**"""

model = BasicCNN()
model.load_state_dict(torch.load('./trained/TSR.pt'))
model = model.to(device)
model.eval()

"""*Classes of Traffic Signs*

This classes are labeled on the basis of available train data
"""

class_names = { 0:'Speed limit (20km/h)',
            1:'Speed limit (30km/h)',
            2:'Speed limit (50km/h)',
            3:'Speed limit (60km/h)',
            4:'Speed limit (70km/h)',
            5:'Speed limit (80km/h)',
            6:'End of speed limit (80km/h)',
            7:'Speed limit (100km/h)',
            8:'Speed limit (120km/h)',
            9:'No passing',
            10:'No passing veh over 3.5 tons',
            11:'Right-of-way at intersection',
            12:'Priority road',
            13:'Yield',
            14:'Stop',
            15:'No vehicles',
            16:'Veh > 3.5 tons prohibited',
            17:'No entry',
            18:'General caution',
            19:'Dangerous curve left',
            20:'Dangerous curve right',
            21:'Double curve',
            22:'Bumpy road',
            23:'Slippery road',
            24:'Road narrows on the right',
            25:'Road work',
            26:'Traffic signals',
            27:'Pedestrians',
            28:'Children crossing',
            29:'Bicycles crossing',
            30:'Beware of ice/snow',
            31:'Wild animals crossing',
            32:'End speed + passing limits',
            33:'Turn right ahead',
            34:'Turn left ahead',
            35:'Ahead only',
            36:'Go straight or right',
            37:'Go straight or left',
            38:'Keep right',
            39:'Keep left',
            40:'Roundabout mandatory',
            41:'End of no passing',
            42:'End no passing veh > 3.5 tons' }

def test_on_img(img):
    image = Image.open(img).convert('RGB')
    x = np.array(image.resize((30, 30)))
    x_t = torch.FloatTensor(x).unsqueeze(0).permute(0, 3, 1, 2) / 255.0
    model.eval()
    with torch.no_grad():
        out = model(x_t.to(device))
        y_pred = out.argmax(1).cpu().numpy()
    return image, y_pred

# Use a test image from the dataset (adjust path to your Test folder)
test_img_path = data_path / "Test" / "00062.png"
if not test_img_path.exists():
    test_img_path = data_path / "test" / "00062.png"
if not test_img_path.exists():
    test_img_path = list((data_path / "Test").glob("*.png"))[0] if (data_path / "Test").exists() else None
if test_img_path:
    plot, prediction = test_on_img(str(test_img_path))
    a = int(prediction[0])
    print("Predicted traffic sign is:", class_names[a])
    plt.imshow(plot)
    plt.show()
else:
    print("No test image found. Update test_img_path to point to a test image.")